import { getAuthSupabase, getCurrentUser } from "@/features/auth/server";
import { resolveBusinessContext, type BusinessRole, type SubjectScope } from "@/features/operating-model/context";
import { listBusinessRoleAssignments, loadContextProjectIdentityMappings, type ManagementSignalRecord } from "@/features/operating-model/persistence";
import { evaluateMetricSignal, parseProjectLevelMetricSignalRules, type MetricSignalRule } from "@/features/operating-model/signal-scanner";
import { writeOperationAudit } from "@/features/security/repository";

export const runtime="nodejs";
function json(body:unknown,status:number,requestId:string){return Response.json(body,{status,headers:{"Cache-Control":"no-store","X-Request-Id":requestId}});}
const SIGNAL_TYPES=["progress","cost","quality","risk","resource","acceptance","cash","benefit","data_quality"];
const OWNER_ROLES:Record<string,string[]>={progress:["pm"],cost:["finance","pm"],quality:["quality","pm"],risk:["pm"],resource:["pm","pmo"],acceptance:["operations","business_owner"],cash:["finance","operations"],benefit:["business_owner","operations"],data_quality:["pmo"]};

function parseRule(row:Record<string,unknown>):MetricSignalRule|null{
  const config=row.configuration&&typeof row.configuration==="object"&&!Array.isArray(row.configuration)?row.configuration as Record<string,unknown>:{};
  const signalType=String(config.signal_type||row.rule_key||"");const metricKey=String(config.metric_key||"");const comparison=String(config.comparison||"");
  const yellow=Number(config.yellow_threshold);const red=Number(config.red_threshold);const review=Number(config.review_after_minutes||1440);
  if(!SIGNAL_TYPES.includes(signalType)||!metricKey||!["greater_than","less_than","variance_percent_above"].includes(comparison)||!Number.isFinite(yellow)||!Number.isFinite(red)||!Number.isFinite(review)||review<=0)return null;
  return{version:String(row.version),signalType:signalType as MetricSignalRule["signalType"],metricKey,comparison:comparison as MetricSignalRule["comparison"],yellowThreshold:yellow,redThreshold:red,routeOnYellow:config.route_on_yellow==="escalation"?"escalation":"action",routeOnRed:config.route_on_red==="action"?"action":"escalation",reviewAfterMinutes:review};
}

export async function POST(request:Request){
  const requestId=crypto.randomUUID();const user=await getCurrentUser();if(!user)return json({error:"UNAUTHORIZED",request_id:requestId},401,requestId);
  const url=new URL(request.url);const role=String(url.searchParams.get("role")||"") as BusinessRole;const orgId=String(url.searchParams.get("org_id")||"");const subjectScope=String(url.searchParams.get("subject_scope")||"") as SubjectScope;const subjectId=String(url.searchParams.get("subject_id")||"");const dataClass=String(url.searchParams.get("data_class")||"") as ManagementSignalRecord["dataClass"];
  if(!["pm","operations","pmo"].includes(role)||!orgId||!subjectScope||!subjectId||!["production","sample","test","diagnostic","unclassified"].includes(dataClass))return json({error:"SCOPED_SCAN_CONTEXT_REQUIRED",request_id:requestId},400,requestId);
  const assignments=await listBusinessRoleAssignments(user.id);if(assignments.status!=="succeeded")return json({error:"P17_STORAGE_NOT_CONFIGURED",detail:assignments.warning,request_id:requestId},503,requestId);
  const context=resolveBusinessContext({user:{id:user.id,systemRole:user.role},assignments:assignments.data??[],requestedRole:role,requestedOrgId:orgId,requestedSubjectScope:subjectScope,requestedSubjectId:subjectId});if(!context)return json({error:"SIGNAL_SCAN_FORBIDDEN",request_id:requestId},403,requestId);
  const mappings=await loadContextProjectIdentityMappings({context,dataClass});if(mappings.status!=="succeeded")return json({error:"PROJECT_SCOPE_MAPPING_FAILED",detail:mappings.warning,request_id:requestId},mappings.status==="not_configured"?503:500,requestId);
  const projectIds=[...new Set((mappings.data??[]).map(item=>item.projectId))];if(projectIds.length===0)return json({status:"succeeded",created:0,refreshed:0,warnings:["当前范围没有稳定项目映射。"],signals:[],source:{type:"supabase",fallback_used:false},request_id:requestId},200,requestId);
  const supabase=getAuthSupabase();
  const [rulesResult,matricesResult,definitionsResult,observationsResult,projectsResult,portfolioLinksResult,rolesResult]=await Promise.all([
    supabase.from("management_rule_versions").select("*").eq("status","active").in("rule_key",SIGNAL_TYPES).or(`org_id.eq.${orgId},org_id.is.null`).order("created_at",{ascending:false}),
    supabase.from("project_level_rule_matrices").select("id,portfolio_id,version,rules,effective_from").eq("org_id",orgId).eq("data_class",dataClass).eq("status","active").order("effective_from",{ascending:false}),
    supabase.from("metric_definitions").select("id,metric_key,version,status").eq("status","active").or(`org_id.eq.${orgId},org_id.is.null`),
    supabase.from("metric_observations").select("*").eq("org_id",orgId).eq("data_class",dataClass).in("project_id",projectIds).order("observed_at",{ascending:false}).limit(1000),
    supabase.from("projects").select("id,project_level,data_class").eq("org_id",orgId).eq("data_class",dataClass).in("id",projectIds),
    supabase.from("portfolio_project_links").select("portfolio_id,project_id").eq("org_id",orgId).in("project_id",projectIds),
    supabase.from("user_business_roles").select("user_id,business_role,subject_scope,subject_id,valid_from,valid_until,status").eq("org_id",orgId).eq("status","active").in("business_role",["pm","operations","pmo","finance","quality","business_owner"]),
  ]);
  const error=[rulesResult,matricesResult,definitionsResult,observationsResult,projectsResult,portfolioLinksResult,rolesResult].find(item=>item.error)?.error;if(error)return json({error:"SIGNAL_SCAN_SOURCE_FAILED",detail:error.message,request_id:requestId},/does not exist|schema cache/i.test(error.message)?503:500,requestId);
  const legacyRules=(rulesResult.data??[]).map(row=>parseRule(row as Record<string,unknown>)).filter((item):item is MetricSignalRule=>Boolean(item));const definitions=new Map((definitionsResult.data??[]).map(row=>[String(row.id),{metricKey:String(row.metric_key),metricVersion:String(row.version)}]));const projects=new Map((projectsResult.data??[]).map(row=>[String(row.id),row]));const activeRoles=rolesResult.data??[];const now=Date.now();
  const portfolioIdsByProject=new Map<string,string[]>();for(const link of portfolioLinksResult.data??[]){const projectId=String(link.project_id);portfolioIdsByProject.set(projectId,[...(portfolioIdsByProject.get(projectId)??[]),String(link.portfolio_id)]);}
  const matrices=(matricesResult.data??[]) as Array<{id:string;portfolio_id:string|null;version:string;rules:Record<string,unknown>;effective_from:string|null}>;
  function matrixRules(projectId:string,projectLevel:string){const portfolios=portfolioIdsByProject.get(projectId)??[];const matrix=matrices.find(item=>item.portfolio_id&&portfolios.includes(String(item.portfolio_id)))??matrices.find(item=>!item.portfolio_id);return matrix?parseProjectLevelMetricSignalRules({matrixVersion:String(matrix.version),projectLevel,rules:matrix.rules||{}}):[];}
  function owner(projectId:string,signalType:string,preferred:unknown){if(preferred)return String(preferred);for(const required of OWNER_ROLES[signalType]??["pmo"]){const match=activeRoles.find(row=>row.business_role===required&&new Date(row.valid_from).getTime()<=now&&(!row.valid_until||new Date(row.valid_until).getTime()>=now)&&((row.subject_scope==="project"&&row.subject_id===projectId)||(row.subject_scope==="organization"&&row.subject_id===orgId)));if(match)return String(match.user_id);}return null;}
  const warnings:string[]=[];if(matrices.length===0&&legacyRules.length===0)warnings.push("没有已审批且阈值完整的PMO分级规则或组织通用规则，未生成展示型信号。");const outputs:Record<string,unknown>[]=[];let created=0;let refreshed=0;const usedRuleVersions=new Set<string>();
  for(const row of observationsResult.data??[]){const definition=definitions.get(String(row.metric_definition_id));if(!definition)continue;const project=projects.get(String(row.project_id));if(!project)continue;const scopedRules=matrixRules(String(row.project_id),String(project.project_level||""));const rule=scopedRules.find(item=>item.metricKey===definition.metricKey&&(!item.metricVersion||item.metricVersion===definition.metricVersion))??legacyRules.find(item=>item.metricKey===definition.metricKey);if(!rule)continue;usedRuleVersions.add(rule.version);const responsible=owner(String(row.project_id),rule.signalType,row.data_owner_user_id);if(!responsible){await supabase.from("business_role_coverage_gaps").upsert({org_id:orgId,subject_scope:"project",subject_id:String(row.project_id),required_business_role:(OWNER_ROLES[rule.signalType]??["pmo"])[0],source_type:"metric_signal_scan",source_id:String(row.id),status:"open",due_at:new Date(Date.now()+86400000).toISOString()},{onConflict:"org_id,subject_scope,subject_id,required_business_role,source_type,source_id"});warnings.push(`指标 ${definition.metricKey} 缺少责任角色，已进入无人承接清单。`);continue;}
    const signal=evaluateMetricSignal({observationId:String(row.id),orgId,projectId:String(row.project_id),projectLevel:String(project.project_level||"*"),dataClass,metricKey:definition.metricKey,currentValue:row.current_value===null?null:Number(row.current_value),baselineValue:row.baseline_value===null?null:Number(row.baseline_value),latestForecastValue:row.latest_forecast_value===null?null:Number(row.latest_forecast_value),periodKey:String(row.period_key),observedAt:String(row.observed_at),freshnessStatus:row.freshness_status,trustStatus:row.trust_status,sourceType:String(row.source_type),sourceId:String(row.source_id),ownerUserId:responsible},rule,new Date());if(!signal)continue;
    const payload={org_id:signal.orgId,project_id:signal.projectId,data_class:signal.dataClass,signal_type:signal.signalType,rule_version:signal.ruleVersion,baseline_version:signal.baselineVersion,severity:signal.severity,route:signal.route,title:signal.title,summary:signal.summary,impact:signal.impact,payload:signal.payload,dedup_key:signal.dedupKey,owner_user_id:signal.ownerUserId,due_at:signal.dueAt,next_review_at:signal.nextReviewAt,metric_observation_ids:signal.metricObservationIds,source_type:signal.sourceType,source_id:signal.sourceId,snapshot_at:signal.snapshotAt,trust_status:signal.trustStatus};const saved=await supabase.rpc("upsert_generic_management_signal_tx",{p_payload:payload,p_actor_user_id:user.id,p_actor_business_role:role,p_request_id:`${requestId}:${row.id}`});if(saved.error)return json({error:"SIGNAL_UPSERT_FAILED",detail:saved.error.message,request_id:requestId},500,requestId);const result=saved.data as {signal?:Record<string,unknown>;created?:boolean};if(result?.signal)outputs.push(result.signal);if(result?.created)created++;else refreshed++;
  }
  await writeOperationAudit({user,action:"generic_management_signal_scan",resourceType:"business_context",resourceId:context.assignmentId,status:"succeeded",severity:"medium",summary:"已按PMO分级矩阵与组织审批规则扫描九类管理信号",detail:{projectCount:projectIds.length,observationCount:(observationsResult.data??[]).length,created,refreshed,ruleVersions:[...usedRuleVersions]},requestId});
  return json({status:"succeeded",created,refreshed,warnings,signals:outputs,source:{type:"supabase",fallback_used:false},request_id:requestId},200,requestId);
}
