import { createHash } from "node:crypto";
import { getAuthSupabase, getCurrentUser } from "@/features/auth/server";
import { buildRetrospectiveCandidates, rankKnowledgeRecommendations, type KnowledgeRecommendationCandidate } from "@/features/operating-model/knowledge-automation";
import { resolveBusinessContext, type BusinessRole, type SubjectScope } from "@/features/operating-model/context";
import { listBusinessRoleAssignments, loadContextProjectIdentityMappings, type ManagementSignalRecord } from "@/features/operating-model/persistence";
import { writeOperationAudit } from "@/features/security/repository";

export const runtime="nodejs";const ROLES=new Set<BusinessRole>(["pm","operations","pmo","quality","sponsor","business_owner"]);
function json(body:unknown,status:number,requestId:string){return Response.json(body,{status,headers:{"Cache-Control":"no-store","X-Request-Id":requestId}});}
async function scopeFor(request:Request){
  const user=await getCurrentUser();if(!user)return{ok:false,error:"UNAUTHORIZED",status:401}as const;const url=new URL(request.url);const role=String(url.searchParams.get("role")||"")as BusinessRole;const orgId=String(url.searchParams.get("org_id")||"");const subjectScope=String(url.searchParams.get("subject_scope")||"")as SubjectScope;const subjectId=String(url.searchParams.get("subject_id")||"");const dataClass=String(url.searchParams.get("data_class")||"")as ManagementSignalRecord["dataClass"];
  if(!ROLES.has(role)||!orgId||!subjectScope||!subjectId||!["production","sample","test","diagnostic","unclassified"].includes(dataClass))return{ok:false,error:"CLOSURE_AUTOMATION_CONTEXT_REQUIRED",status:400}as const;
  const assignments=await listBusinessRoleAssignments(user.id);if(assignments.status!=="succeeded")return{ok:false,error:"P17_STORAGE_NOT_CONFIGURED",detail:assignments.warning,status:503}as const;const context=resolveBusinessContext({user:{id:user.id,systemRole:user.role},assignments:assignments.data??[],requestedRole:role,requestedOrgId:orgId,requestedSubjectScope:subjectScope,requestedSubjectId:subjectId});if(!context)return{ok:false,error:"BUSINESS_CONTEXT_FORBIDDEN",status:403}as const;
  const mappings=await loadContextProjectIdentityMappings({context,dataClass});if(mappings.status!=="succeeded")return{ok:false,error:"PROJECT_SCOPE_MAPPING_FAILED",detail:mappings.warning,status:mappings.status==="not_configured"?503:500}as const;const projectIds=[...new Set((mappings.data??[]).map(item=>item.projectId))];const projectId=url.searchParams.get("project_id")||(context.subjectScope==="project"?context.subjectId:projectIds[0]||"");if(!projectId||!projectIds.includes(projectId))return{ok:false,error:"PROJECT_OUTSIDE_CONTEXT",status:403}as const;
  return{ok:true,user,role,context,dataClass,projectIds,projectId}as const;
}

export async function GET(request:Request){
  const requestId=crypto.randomUUID();const scope=await scopeFor(request);if(!scope.ok)return json({error:scope.error,detail:"detail"in scope?scope.detail:undefined,request_id:requestId},scope.status,requestId);const supabase=getAuthSupabase();
  const [retrospectives,candidates,requests,reuse]=await Promise.all([
    supabase.from("project_retrospectives").select("*").eq("org_id",scope.context.orgId).eq("project_id",scope.projectId).eq("data_class",scope.dataClass).order("created_at",{ascending:false}).limit(50),
    supabase.from("retrospective_knowledge_candidates").select("*").eq("org_id",scope.context.orgId).eq("project_id",scope.projectId).eq("data_class",scope.dataClass).order("created_at",{ascending:false}).limit(200),
    supabase.from("knowledge_recommendation_requests").select("*").eq("org_id",scope.context.orgId).eq("project_id",scope.projectId).eq("data_class",scope.dataClass).order("created_at",{ascending:false}).limit(50),
    supabase.from("knowledge_reuse_events").select("*").eq("org_id",scope.context.orgId).eq("target_project_id",scope.projectId).eq("data_class",scope.dataClass).order("created_at",{ascending:false}).limit(200),
  ]);const error=[retrospectives,candidates,requests,reuse].find(item=>item.error)?.error;if(error)return json({error:"KNOWLEDGE_AUTOMATION_LOAD_FAILED",detail:error.message,request_id:requestId},/does not exist|schema cache/i.test(error.message)?503:500,requestId);
  return json({status:"succeeded",retrospectives:retrospectives.data??[],candidates:candidates.data??[],recommendation_requests:requests.data??[],reuse_events:reuse.data??[],source:{type:"supabase",fallback_used:false},request_id:requestId},200,requestId);
}

export async function POST(request:Request){
  const requestId=crypto.randomUUID();const scope=await scopeFor(request);if(!scope.ok)return json({error:scope.error,detail:"detail"in scope?scope.detail:undefined,request_id:requestId},scope.status,requestId);let body:Record<string,unknown>;try{body=await request.json()as Record<string,unknown>;}catch{return json({error:"INVALID_JSON",request_id:requestId},400,requestId);}const operation=String(body.operation||"");const supabase=getAuthSupabase();let resourceType="knowledge_automation";let resourceId="";
  try{let result:unknown;
    if(operation==="submit_retrospective"){
      if(!["pm","operations","pmo"].includes(scope.role))return json({error:"RETROSPECTIVE_SUBMIT_ROLE_REQUIRED",request_id:requestId},403,requestId);const project=await supabase.from("projects").select("id,name").eq("id",scope.projectId).eq("org_id",scope.context.orgId).eq("data_class",scope.dataClass).maybeSingle();if(project.error)throw project.error;if(!project.data)return json({error:"PROJECT_NOT_FOUND",request_id:requestId},404,requestId);
      const evidenceIds=Array.isArray(body.evidence_ids)?body.evidence_ids.map(String).filter(Boolean):[];const candidates=buildRetrospectiveCandidates({projectId:scope.projectId,projectName:String(project.data.name||"项目"),objectives:String(body.objectives||""),outcomes:String(body.outcomes||""),deviations:String(body.deviations||""),rootCauses:String(body.root_causes||""),keyDecisions:String(body.key_decisions||""),actionEffects:String(body.action_effects||""),lessons:String(body.lessons||""),applicabilityConditions:String(body.applicability_conditions||""),templateGaps:String(body.template_gaps||""),governanceSuggestions:String(body.governance_suggestions||""),evidenceIds,improvementOwnerUserId:String(body.improvement_owner_user_id||""),improvementDueAt:String(body.improvement_due_at||"")});
      const saved=await supabase.rpc("submit_project_retrospective_tx",{p_org_id:scope.context.orgId,p_project_id:scope.projectId,p_data_class:scope.dataClass,p_input:{objectives:body.objectives,outcomes:body.outcomes,deviations:body.deviations,root_causes:body.root_causes,key_decisions:body.key_decisions,action_effects:body.action_effects,lessons:body.lessons,applicability_conditions:body.applicability_conditions,evidence_ids:evidenceIds},p_candidates:candidates.map(item=>({candidate_type:item.candidateType,title:item.title,summary:item.summary,applicability_conditions:item.applicabilityConditions,evidence_ids:item.evidenceIds,suggested_action:item.suggestedAction,owner_user_id:item.ownerUserId,due_at:item.dueAt})),p_actor_user_id:scope.user.id,p_request_id:requestId});if(saved.error)throw saved.error;result=saved.data;resourceType="project_retrospective";resourceId=String((saved.data as {retrospective?:{id?:string}})?.retrospective?.id||"");
    }else if(operation==="review_candidate"){
      if(!["pmo","quality"].includes(scope.role))return json({error:"KNOWLEDGE_REVIEW_ROLE_REQUIRED",request_id:requestId},403,requestId);const id=String(body.candidate_id||"");const decision=body.decision==="approve"?"approved":body.decision==="reject"?"rejected":"";const note=String(body.review_note||"").trim();if(!id||!decision||!note)return json({error:"CANDIDATE_DECISION_AND_NOTE_REQUIRED",request_id:requestId},400,requestId);const updated=await supabase.from("retrospective_knowledge_candidates").update({status:decision,review_note:note,reviewed_by:scope.user.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("org_id",scope.context.orgId).eq("project_id",scope.projectId).eq("data_class",scope.dataClass).eq("status","pending_review").select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"CANDIDATE_REVIEW_CONFLICT",request_id:requestId},409,requestId);result=updated.data;resourceType="retrospective_candidate";resourceId=id;
    }else if(operation==="materialize_candidate"){
      if(!["pmo","quality"].includes(scope.role))return json({error:"KNOWLEDGE_REVIEW_ROLE_REQUIRED",request_id:requestId},403,requestId);const id=String(body.candidate_id||"");const candidate=await supabase.from("retrospective_knowledge_candidates").select("id,summary").eq("id",id).eq("org_id",scope.context.orgId).eq("project_id",scope.projectId).eq("data_class",scope.dataClass).maybeSingle();if(candidate.error)throw candidate.error;if(!candidate.data)return json({error:"CANDIDATE_NOT_FOUND",request_id:requestId},404,requestId);const hash=createHash("sha256").update(String(candidate.data.summary)).digest("hex");const materialized=await supabase.rpc("materialize_retrospective_candidate_tx",{p_candidate_id:id,p_actor_user_id:scope.user.id,p_actor_name:scope.user.name||scope.user.email,p_actor_business_role:scope.role,p_content_hash:hash,p_request_id:requestId});if(materialized.error)throw materialized.error;result=materialized.data;resourceType="retrospective_candidate";resourceId=id;
    }else if(operation==="recommend_knowledge"){
      const triggerType=["new_project","management_signal","manual"].includes(String(body.trigger_type))?String(body.trigger_type):"manual";const scenario=String(body.scenario||"").trim();if(!scenario)return json({error:"RECOMMENDATION_SCENARIO_REQUIRED",request_id:requestId},400,requestId);const project=await supabase.from("projects").select("id,name,project_level,project_type").eq("id",scope.projectId).eq("org_id",scope.context.orgId).eq("data_class",scope.dataClass).maybeSingle();if(project.error)throw project.error;if(!project.data)return json({error:"PROJECT_NOT_FOUND",request_id:requestId},404,requestId);
      const [items,templates,decisions]=await Promise.all([supabase.from("knowledge_items").select("id,title,status,domains,tags,applicable_scenarios,metadata,page_id,confidentiality").eq("status","published").limit(500),supabase.from("knowledge_template_directory_items").select("id,template_key,title,category,description,linked_knowledge_page_ids,metadata").eq("lifecycle_status","active").limit(200),supabase.from("decision_briefs").select("id,title,status,project_id,impact_summary,updated_at").eq("org_id",scope.context.orgId).eq("data_class",scope.dataClass).in("status",["effect_reviewed","closed"]).order("updated_at",{ascending:false}).limit(100)]);const error=items.error||templates.error||decisions.error;if(error)throw error;
      const rawItems=items.data??[];const sourceProjectIds=[...new Set(rawItems.map(item=>String((item.metadata as Record<string,unknown>|null)?.source_project_id||"")).filter(Boolean))];const sourceProjects=sourceProjectIds.length?await supabase.from("projects").select("id").eq("org_id",scope.context.orgId).in("id",sourceProjectIds):{data:[],error:null};if(sourceProjects.error)throw sourceProjects.error;const sameOrgProjects=new Set((sourceProjects.data??[]).map(item=>String(item.id)));const visibleItems=rawItems.filter(item=>{const metadata=(item.metadata as Record<string,unknown>|null)??{};const sourceProjectId=String(metadata.source_project_id||"");const metadataOrg=String(metadata.org_id||"");if(metadataOrg&&metadataOrg!==scope.context.orgId)return false;if(sourceProjectId&&!sameOrgProjects.has(sourceProjectId))return false;return item.confidentiality!=="restricted"||["pmo","quality","sponsor"].includes(scope.role);});const recommendationCandidates:KnowledgeRecommendationCandidate[]=visibleItems.map(item=>({id:String(item.id),title:String(item.title),status:String(item.status),domains:Array.isArray(item.domains)?item.domains.map(String):[],tags:Array.isArray(item.tags)?item.tags.map(String):[],applicableScenarios:Array.isArray(item.applicable_scenarios)?item.applicable_scenarios.map(String):[],metadata:(item.metadata as Record<string,unknown>|null)??{}}));const tags=Array.isArray(body.tags)?body.tags.map(String):[];const ranked=rankKnowledgeRecommendations({projectLevel:String(project.data.project_level||""),projectType:String(project.data.project_type||""),scenario,tags},recommendationCandidates).slice(0,10);const pageIds=new Set(ranked.map(rec=>String(visibleItems.find(item=>item.id===rec.knowledgeItemId)?.page_id||"")));const templateResults=(templates.data??[]).map(template=>{const linked=Array.isArray(template.linked_knowledge_page_ids)?template.linked_knowledge_page_ids.map(String):[];const score=linked.filter(id=>pageIds.has(id)).length*3+(JSON.stringify(template.metadata||{}).includes(scenario)?2:0);return{template_id:template.id,template_key:template.template_key,title:template.title,score,reasons:[...(score>=3?["关联相似知识"]:[]),...(JSON.stringify(template.metadata||{}).includes(scenario)?["场景匹配"]:[])]};}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score).slice(0,10);const decisionResults=(decisions.data??[]).map(decision=>({decision_brief_id:decision.id,title:decision.title,project_id:decision.project_id,impact_summary:decision.impact_summary,reason:decision.project_id===scope.projectId?"本项目历史决策":"同组织已完成效果复核的决策"})).slice(0,10);
      const recommendations={knowledge:ranked,templates:templateResults,decisions:decisionResults};const created=await supabase.from("knowledge_recommendation_requests").insert({org_id:scope.context.orgId,project_id:scope.projectId,trigger_type:triggerType,trigger_source_id:String(body.trigger_source_id||""),scenario,criteria:{project_level:project.data.project_level,project_type:project.data.project_type,tags},recommendations,status:"generated",requested_by:scope.user.id,data_class:scope.dataClass,request_id:requestId}).select("*").single();if(created.error)throw created.error;
      const knowledgeRows=ranked.filter(item=>item.score>0).map(item=>{const source=(items.data??[]).find(row=>row.id===item.knowledgeItemId);return{org_id:scope.context.orgId,knowledge_item_id:item.knowledgeItemId,source_project_id:(source?.metadata as Record<string,unknown>|null)?.source_project_id||null,target_project_id:scope.projectId,recommendation_reason:item.reasons.join("；")||"人工请求的相似知识",applicability:{scenario,score:item.score},status:"recommended",actor_user_id:scope.user.id,data_class:scope.dataClass,recommendation_request_id:created.data.id};});if(knowledgeRows.length){const reused=await supabase.from("knowledge_reuse_events").insert(knowledgeRows);if(reused.error)throw reused.error;}result={request:created.data,recommendations};resourceType="knowledge_recommendation_request";resourceId=created.data.id;
    }else return json({error:"UNSUPPORTED_OPERATION",request_id:requestId},400,requestId);
    await writeOperationAudit({user:scope.user,action:`knowledge_automation_${operation}`,resourceType,resourceId,status:"succeeded",severity:"medium",summary:`知识自动化动作：${operation}`,detail:{projectId:scope.projectId,role:scope.role,dataClass:scope.dataClass},requestId});return json({status:"succeeded",result,source:{type:"supabase",fallback_used:false},request_id:requestId},200,requestId);
  }catch(error){const detail=error instanceof Error?error.message:"unknown";return json({error:"KNOWLEDGE_AUTOMATION_OPERATION_FAILED",detail,request_id:requestId},/REQUIRED|FORBIDDEN/.test(detail)?403:/CONFLICT|NOT_APPROVED/.test(detail)?409:/does not exist|schema cache/i.test(detail)?503:500,requestId);}
}
