"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Row = Record<string, unknown>;
type Workspace = { error?: string; detail?: string; organizations?: Row[]; policies?: Row[]; recusals?: Row[]; coverage_gaps?: Row[]; metrics?: Row[]; observations?: Row[]; sync_contracts?: Row[] };
const ROLES = ["pm","operations","pmo","ceo","sponsor","business_owner","finance","quality"];
function csv(value: string) { return value.split(",").map(item => item.trim()).filter(Boolean); }
function show(value: unknown, fallback="-") { return value === null || value === undefined || value === "" ? fallback : String(value); }

export default function OperatingModelAdminPage() {
  const [data,setData]=useState<Workspace>({}); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [policy,setPolicy]=useState({orgId:"",key:"",role:"pm",objectType:"project",action:"read",effect:"allow",states:"*",levels:"*",decisionLevels:"*",maxAmount:""});
  const [metric,setMetric]=useState({orgId:"",key:"",version:"v1",name:"",definition:"",freshness:"1440"});
  const [recusal,setRecusal]=useState({orgId:"",userId:"",role:"pmo",scope:"project",subjectId:"",reasonCode:"CONFLICT_OF_INTEREST",reasonDetail:"",validUntil:""});
  const [sync,setSync]=useState({orgId:"",factKey:"",source:"feishu",target:"ai-pm",direction:"inbound",refresh:"event+daily reconciliation",idempotency:"source_record_id+version",deletion:"revoke mapping and retain audit",compensation:"retry then create reconciliation task",ownerRole:"pmo"});
  const [observation,setObservation]=useState({orgId:"",definitionId:"",scope:"project",subjectId:"",projectId:"",period:"",currentValue:"",baselineValue:"",sourceType:"feishu_record",sourceId:"",sourceStatus:"verified",observedAt:"",dataClass:"production",ownerUserId:""});

  const load=useCallback(async()=>{try{const response=await fetch("/api/admin/operating-model",{cache:"no-store"});const body=await response.json() as Workspace;if(!response.ok)throw new Error(body.detail||body.error||"运行模型加载失败");setData(body);}catch(error){setNotice(error instanceof Error?error.message:"运行模型加载失败");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function mutate(body:Row,success:string){setBusy(true);setNotice("");try{const response=await fetch("/api/admin/operating-model",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.detail||result.error||"操作失败");setNotice(success);await load();}catch(error){setNotice(error instanceof Error?error.message:"操作失败");}finally{setBusy(false);}}

  return <main style={{minHeight:"100vh",background:"var(--bg)"}}><header style={{padding:"15px 28px",borderBottom:"1px solid var(--border)",background:"var(--surface)",display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}><Link href="/admin/security" style={{color:"var(--text2)",textDecoration:"none"}}>← 返回安全中心</Link><strong>P17 运行模型控制台</strong><Link href="/admin/operating-model/project-identities" className="btn-secondary" style={{textDecoration:"none",marginLeft:"auto"}}>稳定项目身份迁移</Link></header><div style={{maxWidth:1440,margin:"0 auto",padding:28}}>
    <section className="card" style={{marginBottom:18}}><h1 style={{fontSize:"1.4rem"}}>权限、回避、指标口径和同步契约</h1><p style={{color:"var(--text2)",lineHeight:1.8,marginTop:8}}>这里维护业务角色在不同对象状态、项目等级、决策级别和金额范围内可以做什么；同时管理回避、无人承接、数据新鲜度与事实同步责任。草稿经明确启用后才生效。</p></section>
    {notice&&<section className="card" style={{marginBottom:18,borderColor:"rgba(245,158,11,.45)"}}>{notice}</section>}
    <section className="card" style={{marginBottom:18}}><h2>授权策略</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,marginTop:10}}><input className="input" placeholder="组织 UUID，空=全局" value={policy.orgId} onChange={e=>setPolicy({...policy,orgId:e.target.value})}/><input className="input" placeholder="策略键" value={policy.key} onChange={e=>setPolicy({...policy,key:e.target.value})}/><select className="input" value={policy.role} onChange={e=>setPolicy({...policy,role:e.target.value})}>{ROLES.map(item=><option key={item}>{item}</option>)}</select><input className="input" placeholder="对象类型" value={policy.objectType} onChange={e=>setPolicy({...policy,objectType:e.target.value})}/><input className="input" placeholder="动作" value={policy.action} onChange={e=>setPolicy({...policy,action:e.target.value})}/><select className="input" value={policy.effect} onChange={e=>setPolicy({...policy,effect:e.target.value})}><option value="allow">允许</option><option value="deny">显式拒绝</option></select><input className="input" placeholder="状态，逗号分隔" value={policy.states} onChange={e=>setPolicy({...policy,states:e.target.value})}/><input className="input" placeholder="项目等级" value={policy.levels} onChange={e=>setPolicy({...policy,levels:e.target.value})}/><input className="input" placeholder="决策级别" value={policy.decisionLevels} onChange={e=>setPolicy({...policy,decisionLevels:e.target.value})}/><input className="input" type="number" placeholder="金额上限，可空" value={policy.maxAmount} onChange={e=>setPolicy({...policy,maxAmount:e.target.value})}/></div><button className="btn-primary" disabled={busy} style={{marginTop:10}} onClick={()=>void mutate({operation:"create_policy",org_id:policy.orgId||null,policy_key:policy.key,business_role:policy.role,object_type:policy.objectType,action:policy.action,effect:policy.effect,allowed_states:csv(policy.states),project_levels:csv(policy.levels),decision_levels:csv(policy.decisionLevels),max_amount:policy.maxAmount},"授权策略草稿已创建。")}>创建策略草稿</button><div style={{display:"grid",gap:8,marginTop:12}}>{(data.policies??[]).map(row=><article key={show(row.id)} style={{padding:10,border:"1px solid var(--border)",borderRadius:9}}><strong>{show(row.policy_key)}</strong> <span className="tag tag-blue">{show(row.status)}</span><p style={{color:"var(--text2)",marginTop:5}}>{show(row.effect)} · {show(row.business_role)} · {show(row.object_type)} / {show(row.action)} · 金额上限 {show(row.max_amount,"不限")}</p>{row.status==="draft"&&<button className="btn-primary" disabled={busy} onClick={()=>void mutate({operation:"activate_policy",id:row.id},"策略已审批启用。")}>审批启用</button>}{row.status==="active"&&<button className="btn-secondary" disabled={busy} onClick={()=>void mutate({operation:"retire_policy",id:row.id},"策略已停用。")}>停用</button>}</article>)}</div></section>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(420px,1fr))",gap:18}}>
      <section className="card"><h2>指标字典与新鲜度</h2><div style={{display:"grid",gap:8,marginTop:10}}><input className="input" placeholder="组织 UUID，可空" value={metric.orgId} onChange={e=>setMetric({...metric,orgId:e.target.value})}/><input className="input" placeholder="指标键" value={metric.key} onChange={e=>setMetric({...metric,key:e.target.value})}/><input className="input" placeholder="版本" value={metric.version} onChange={e=>setMetric({...metric,version:e.target.value})}/><input className="input" placeholder="中文名称" value={metric.name} onChange={e=>setMetric({...metric,name:e.target.value})}/><textarea className="input" placeholder="指标定义与口径" value={metric.definition} onChange={e=>setMetric({...metric,definition:e.target.value})}/><input className="input" type="number" placeholder="新鲜度SLA（分钟）" value={metric.freshness} onChange={e=>setMetric({...metric,freshness:e.target.value})}/></div><button className="btn-primary" disabled={busy} style={{marginTop:8}} onClick={()=>void mutate({operation:"create_metric",org_id:metric.orgId||null,metric_key:metric.key,version:metric.version,name:metric.name,definition:metric.definition,freshness_sla_minutes:Number(metric.freshness)},"指标草稿已创建。")}>创建指标草稿</button><div style={{marginTop:10}}>{(data.metrics??[]).map(row=><p key={show(row.id)}>{show(row.name)} · {show(row.version)} · {show(row.status)} {row.status==="draft"&&<button className="btn-secondary" onClick={()=>void mutate({operation:"activate_metric",id:row.id},"指标已启用。")}>启用</button>}</p>)}</div></section>
      <section className="card"><h2>回避与利益冲突</h2><div style={{display:"grid",gap:8,marginTop:10}}><input className="input" placeholder="组织 UUID" value={recusal.orgId} onChange={e=>setRecusal({...recusal,orgId:e.target.value})}/><input className="input" placeholder="用户 UUID" value={recusal.userId} onChange={e=>setRecusal({...recusal,userId:e.target.value})}/><select className="input" value={recusal.role} onChange={e=>setRecusal({...recusal,role:e.target.value})}>{ROLES.map(item=><option key={item}>{item}</option>)}</select><input className="input" placeholder="主体范围 project/portfolio/..." value={recusal.scope} onChange={e=>setRecusal({...recusal,scope:e.target.value})}/><input className="input" placeholder="主体稳定ID" value={recusal.subjectId} onChange={e=>setRecusal({...recusal,subjectId:e.target.value})}/><textarea className="input" placeholder="回避原因" value={recusal.reasonDetail} onChange={e=>setRecusal({...recusal,reasonDetail:e.target.value})}/></div><button className="btn-primary" disabled={busy} style={{marginTop:8}} onClick={()=>void mutate({operation:"create_recusal",org_id:recusal.orgId,user_id:recusal.userId,business_role:recusal.role,subject_scope:recusal.scope,subject_id:recusal.subjectId,reason_code:recusal.reasonCode,reason_detail:recusal.reasonDetail,valid_until:recusal.validUntil||null},"回避规则已生效。")}>登记回避</button><div style={{marginTop:10}}>{(data.recusals??[]).map(row=><p key={show(row.id)}>{show(row.business_role)} · {show(row.subject_id)} · {show(row.status)} {row.status==="active"&&<button className="btn-secondary" onClick={()=>void mutate({operation:"release_recusal",id:row.id},"回避已解除。")}>解除</button>}</p>)}</div></section>
    </div>
    <section className="card" style={{marginTop:18}}><h2>事实同步契约</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8,marginTop:10}}><input className="input" placeholder="组织 UUID，可空" value={sync.orgId} onChange={e=>setSync({...sync,orgId:e.target.value})}/><input className="input" placeholder="事实键" value={sync.factKey} onChange={e=>setSync({...sync,factKey:e.target.value})}/><input className="input" placeholder="权威来源" value={sync.source} onChange={e=>setSync({...sync,source:e.target.value})}/><input className="input" placeholder="目标系统" value={sync.target} onChange={e=>setSync({...sync,target:e.target.value})}/><select className="input" value={sync.direction} onChange={e=>setSync({...sync,direction:e.target.value})}>{["inbound","outbound","bidirectional","reference_only"].map(item=><option key={item}>{item}</option>)}</select><input className="input" placeholder="对账Owner角色" value={sync.ownerRole} onChange={e=>setSync({...sync,ownerRole:e.target.value})}/></div><button className="btn-primary" disabled={busy} style={{marginTop:8}} onClick={()=>void mutate({operation:"create_sync_contract",org_id:sync.orgId||null,fact_key:sync.factKey,source_system:sync.source,target_system:sync.target,direction:sync.direction,refresh_policy:sync.refresh,idempotency_definition:sync.idempotency,deletion_semantics:sync.deletion,compensation_strategy:sync.compensation,reconciliation_owner_role:sync.ownerRole},"同步契约草稿已创建。")}>创建同步契约</button><div style={{marginTop:10}}>{(data.sync_contracts??[]).map(row=><p key={show(row.id)}>{show(row.fact_key)} · {show(row.source_system)} → {show(row.target_system)} · {show(row.status)} {row.status==="draft"&&<button className="btn-secondary" onClick={()=>void mutate({operation:"activate_sync_contract",id:row.id},"同步契约已启用。")}>启用</button>}</p>)}</div></section>
    <section className="card" style={{marginTop:18}}><h2>记录指标事实并判定可信度</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8,marginTop:10}}><input className="input" placeholder="组织 UUID" value={observation.orgId} onChange={e=>setObservation({...observation,orgId:e.target.value})}/><input className="input" placeholder="指标定义 UUID" value={observation.definitionId} onChange={e=>setObservation({...observation,definitionId:e.target.value})}/><input className="input" placeholder="主体稳定ID" value={observation.subjectId} onChange={e=>setObservation({...observation,subjectId:e.target.value})}/><input className="input" placeholder="项目 UUID，可空" value={observation.projectId} onChange={e=>setObservation({...observation,projectId:e.target.value})}/><input className="input" placeholder="期间，如2026-07" value={observation.period} onChange={e=>setObservation({...observation,period:e.target.value})}/><input className="input" type="number" placeholder="当前值" value={observation.currentValue} onChange={e=>setObservation({...observation,currentValue:e.target.value})}/><input className="input" type="number" placeholder="基线值" value={observation.baselineValue} onChange={e=>setObservation({...observation,baselineValue:e.target.value})}/><input className="input" placeholder="来源记录ID" value={observation.sourceId} onChange={e=>setObservation({...observation,sourceId:e.target.value})}/><input className="input" type="datetime-local" value={observation.observedAt} onChange={e=>setObservation({...observation,observedAt:e.target.value})}/><input className="input" placeholder="数据Owner UUID" value={observation.ownerUserId} onChange={e=>setObservation({...observation,ownerUserId:e.target.value})}/></div><button className="btn-primary" disabled={busy} style={{marginTop:8}} onClick={()=>void mutate({operation:"record_metric_observation",org_id:observation.orgId,metric_definition_id:observation.definitionId,subject_scope:observation.scope,subject_id:observation.subjectId,project_id:observation.projectId||null,period_key:observation.period,current_value:observation.currentValue||null,baseline_value:observation.baselineValue||null,source_type:observation.sourceType,source_id:observation.sourceId,source_status:observation.sourceStatus,observed_at:observation.observedAt?new Date(observation.observedAt).toISOString():"",data_owner_user_id:observation.ownerUserId||null,data_class:observation.dataClass},"指标事实已记录并完成新鲜度/可信度判定。")}>记录指标事实</button><div style={{marginTop:10}}>{(data.observations??[]).slice(0,30).map(row=><p key={show(row.id)}>{show(row.period_key)} · {show(row.current_value)} · {show(row.freshness_status)} · {show(row.trust_status)}</p>)}</div></section>
    <section className="card" style={{marginTop:18}}><h2>无人承接事项</h2><div style={{display:"flex",gap:8,marginTop:8}}><select className="input" value={policy.orgId} onChange={e=>setPolicy({...policy,orgId:e.target.value})}><option value="">选择组织</option>{(data.organizations??[]).map(row=><option key={show(row.id)} value={show(row.id)}>{show(row.name)}</option>)}</select><button className="btn-primary" disabled={busy||!policy.orgId} onClick={()=>void mutate({operation:"scan_coverage_gaps",org_id:policy.orgId},"PM、运营、PMO责任覆盖已扫描。")}>扫描无人承接</button></div>{(data.coverage_gaps??[]).length===0&&<p style={{color:"var(--text2)",marginTop:8}}>当前没有已登记的角色覆盖缺口。</p>}{(data.coverage_gaps??[]).map(row=><p key={show(row.id)}>{show(row.required_business_role)} · {show(row.subject_id)} · {show(row.status)} {row.status!=="closed"&&<button className="btn-secondary" onClick={()=>void mutate({operation:"resolve_coverage_gap",id:row.id,resolution_note:"管理员确认已补齐责任角色"},"覆盖缺口已关闭。")}>确认已补齐</button>}</p>)}</section>
  </div></main>;
}
