"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Run = { id:string; status:string; source_container_id:string; preview_snapshot?:{summary?:Record<string,number>;invalid_records?:unknown[]}; applied_summary?:Record<string,number>; verification_snapshot?:{matched?:number;mismatched?:number;conflicts_quarantined?:number;mismatches?:unknown[]}; cutover_mode?:string|null;read_percentage?:number|null;rollback_reason?:string|null;created_at:string };
type Config = { id:string; mode:string;read_percentage:number;active_run_id?:string|null;updated_at:string };
type Payload = { error?:string;detail?:string;preview?:{status:string;warning?:string;preview?:{plan:{summary:Record<string,number>};invalidRecords:unknown[]}};runs?:Run[];configs?:Config[] };

function key() { return `identity-preview:${new Date().toISOString().slice(0,10)}:${crypto.randomUUID()}`; }

export default function ProjectIdentityMigrationPage() {
  const [data,setData]=useState<Payload>({}); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState(""); const [mode,setMode]=useState("dual_read"); const [percentage,setPercentage]=useState("10"); const [rollbackReason,setRollbackReason]=useState("");
  const load=useCallback(async()=>{setError("");try{const response=await fetch("/api/admin/operating-model/project-identities",{cache:"no-store"});const body=await response.json() as Payload;if(!response.ok)throw new Error(body.detail||body.error||"稳定项目身份控制面加载失败");setData(body);setSelected(current=>current||(body.runs?.find(item=>!["rolled_back","cancelled"].includes(item.status))?.id??body.runs?.[0]?.id??""));}catch(caught){setError(caught instanceof Error?caught.message:"加载失败");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function operate(operation:string,extra:Record<string,unknown>={}){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/operating-model/project-identities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation,run_id:selected,...extra})});const body=await response.json() as {error?:string;detail?:string;run_id?:string};if(!response.ok)throw new Error(body.detail||body.error||"操作失败");if(body.run_id)setSelected(body.run_id);setNotice("迁移动作已保存并写入审计，可刷新或换设备继续。");await load();}catch(caught){setError(caught instanceof Error?caught.message:"操作失败");}finally{setBusy(false);}}
  const current=data.runs?.find(item=>item.id===selected); const summary=data.preview?.preview?.plan.summary;
  return <main style={{minHeight:"100vh",background:"var(--bg)"}}><header style={{padding:"15px 28px",borderBottom:"1px solid var(--border)",background:"var(--surface)",display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}><Link href="/admin/operating-model" style={{color:"var(--text2)",textDecoration:"none"}}>← 返回运行模型控制台</Link><strong>稳定项目身份迁移</strong><span className="tag tag-purple">预览 → 应用 → 双读验证 → 灰度切换 → 非破坏回滚</span></header>
    <div style={{maxWidth:1380,margin:"0 auto",padding:28}}>
      <section className="card" style={{marginBottom:16}}><h1 style={{fontSize:"1.35rem"}}>把飞书记录可靠映射为唯一 project_id</h1><p style={{color:"var(--text2)",lineHeight:1.8,marginTop:8}}>系统先盘点重复编号、孤儿和冲突，再保存一次不可变预览。应用后必须做旧字段与稳定ID双读对比，只有全部匹配才能灰度切换。回滚只撤销或恢复映射，不删除飞书记录、项目或历史审计。</p></section>
      {(error||notice)&&<section className="card" style={{marginBottom:16,borderColor:error?"rgba(239,68,68,.45)":"rgba(16,185,129,.45)",color:error?"var(--red)":"var(--green)"}}>{error||notice}</section>}
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(330px,1fr))",gap:16}}>
        <section className="card"><h2>1. 飞书盘点预览</h2>{data.preview?.status==="succeeded"&&summary?<><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:12}}>{Object.entries(summary).map(([label,value])=><div className="stat-card" key={label}><div className="stat-num">{value}</div><div className="stat-label">{label}</div></div>)}</div><p style={{color:"var(--text2)",marginTop:10}}>无效记录：{data.preview.preview?.invalidRecords.length??0}；冲突不会自动按项目名称合并。</p><button className="btn-primary" disabled={busy} onClick={()=>void operate("create_preview",{confirmation:"CREATE_IDENTITY_PREVIEW",idempotency_key:key()})}>保存本次预览</button></>:<p style={{color:"var(--amber)",lineHeight:1.7}}>{data.preview?.warning||"飞书项目台账尚未就绪。"}</p>}</section>
        <section className="card"><h2>2. 选择迁移批次</h2><select className="input" style={{marginTop:10}} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">请选择</option>{(data.runs??[]).map(item=><option key={item.id} value={item.id}>{new Date(item.created_at).toLocaleString("zh-CN")} · {item.status}</option>)}</select>{current&&<div style={{marginTop:12,lineHeight:1.8,color:"var(--text2)"}}><p>当前状态：<span className="tag tag-blue">{current.status}</span></p><p>应用：{JSON.stringify(current.applied_summary??{})}</p><p>验证：匹配 {current.verification_snapshot?.matched??0}，不匹配 {current.verification_snapshot?.mismatched??0}，隔离冲突 {current.verification_snapshot?.conflicts_quarantined??0}</p><p>切换：{current.cutover_mode||"未切换"} {current.read_percentage??0}%</p></div>}</section>
      </div>
      {current&&<section className="card" style={{marginTop:16}}><h2>3. 按阶段推进</h2><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:12}}><button className="btn-primary" disabled={busy||current.status!=="previewed"} onClick={()=>void operate("apply",{confirmation:"APPLY_PROJECT_IDENTITY_BACKFILL"})}>应用稳定映射</button><button className="btn-primary" disabled={busy||!["applied","blocked","verified"].includes(current.status)} onClick={()=>void operate("verify",{confirmation:"VERIFY_DUAL_READ"})}>执行双读验证</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:8,marginTop:14}}><select className="input" value={mode} onChange={event=>{setMode(event.target.value);setPercentage(event.target.value==="stable_id"?"100":"10");}}><option value="dual_read">双读灰度</option><option value="stable_id">稳定ID正式读取</option></select><input className="input" type="number" min={mode==="stable_id"?100:1} max={mode==="stable_id"?100:99} value={percentage} onChange={event=>setPercentage(event.target.value)}/><button className="btn-primary" disabled={busy||!["verified","cutover"].includes(current.status)} onClick={()=>void operate("cutover",{mode,read_percentage:Number(percentage),confirmation:"CUTOVER_STABLE_PROJECT_ID"})}>确认切换</button></div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,marginTop:14}}><input className="input" placeholder="填写回滚原因和影响范围" value={rollbackReason} onChange={event=>setRollbackReason(event.target.value)}/><button className="btn-secondary" disabled={busy||!rollbackReason||!["applied","verified","blocked","cutover"].includes(current.status)} onClick={()=>void operate("rollback",{reason:rollbackReason,confirmation:"ROLLBACK_PROJECT_IDENTITY"})}>非破坏回滚</button></div></section>}
      <section className="card" style={{marginTop:16}}><h2>当前读取配置</h2>{(data.configs??[]).length===0?<p style={{color:"var(--text2)"}}>尚未切换，继续使用旧读取路径。</p>:(data.configs??[]).map(item=><p key={item.id} style={{marginTop:8}}>{item.mode} · {item.read_percentage}% · {new Date(item.updated_at).toLocaleString("zh-CN")}</p>)}</section>
    </div></main>;
}
