import { getAuthSupabase, requireAdmin } from "@/features/auth/server";
import { assessMetricTrust } from "@/features/operating-model/operating-contracts";
import { writeOperationAudit } from "@/features/security/repository";

export const runtime = "nodejs";
function json(body: unknown, status: number, requestId: string) { return Response.json(body, { status, headers: { "Cache-Control": "no-store", "X-Request-Id": requestId } }); }
function text(body: Record<string, unknown>, key: string) { return String(body[key] || "").trim(); }

export async function GET() {
  const requestId = crypto.randomUUID(); const admin = await requireAdmin(); if (!admin) return json({ error: "FORBIDDEN", request_id: requestId }, 403, requestId);
  const supabase = getAuthSupabase();
  const [organizations, policies, recusals, coverage, metrics, observations, syncContracts] = await Promise.all([
    supabase.from("organizations").select("id,org_code,name,status").order("name"),
    supabase.from("business_authorization_policies").select("*").order("updated_at", { ascending: false }).limit(300),
    supabase.from("business_role_recusals").select("*").order("updated_at", { ascending: false }).limit(300),
    supabase.from("business_role_coverage_gaps").select("*").order("updated_at", { ascending: false }).limit(300),
    supabase.from("metric_definitions").select("*").order("created_at", { ascending: false }).limit(300),
    supabase.from("metric_observations").select("*").order("observed_at", { ascending: false }).limit(300),
    supabase.from("data_sync_contracts").select("*").order("updated_at", { ascending: false }).limit(300),
  ]);
  const error = [organizations, policies, recusals, coverage, metrics, observations, syncContracts].find(item => item.error)?.error;
  if (error) return json({ error: "OPERATING_MODEL_LOAD_FAILED", detail: error.message, request_id: requestId }, /does not exist|schema cache/i.test(error.message) ? 503 : 500, requestId);
  return json({ status: "succeeded", organizations: organizations.data ?? [], policies: policies.data ?? [], recusals: recusals.data ?? [], coverage_gaps: coverage.data ?? [], metrics: metrics.data ?? [], observations: observations.data ?? [], sync_contracts: syncContracts.data ?? [], source: { type: "supabase", fallback_used: false }, request_id: requestId }, 200, requestId);
}

export async function POST(request: Request) {
  const requestId = crypto.randomUUID(); const admin = await requireAdmin(); if (!admin) return json({ error: "FORBIDDEN", request_id: requestId }, 403, requestId);
  let body: Record<string, unknown>; try { body = await request.json() as Record<string, unknown>; } catch { return json({ error: "INVALID_JSON", request_id: requestId }, 400, requestId); }
  const operation = text(body, "operation"); const supabase = getAuthSupabase(); let resourceType = "operating_model"; let resourceId = "";
  try {
    let result: unknown;
    if (operation === "create_policy") {
      const required = ["policy_key","business_role","object_type","action"]; if (required.some(key => !text(body,key))) return json({ error: "POLICY_REQUIRED_FIELDS_MISSING", request_id: requestId }, 400, requestId);
      const created = await supabase.from("business_authorization_policies").insert({ org_id: body.org_id || null, policy_key: text(body,"policy_key"), version: Number(body.version || 1), status: "draft", effect: body.effect === "deny" ? "deny" : "allow", business_role: text(body,"business_role"), object_type: text(body,"object_type"), action: text(body,"action"), allowed_states: Array.isArray(body.allowed_states) ? body.allowed_states : ["*"], project_levels: Array.isArray(body.project_levels) ? body.project_levels : ["*"], decision_levels: Array.isArray(body.decision_levels) ? body.decision_levels : ["*"], max_amount: body.max_amount === "" || body.max_amount === null || body.max_amount === undefined ? null : Number(body.max_amount), sensitive_fields: Array.isArray(body.sensitive_fields) ? body.sensitive_fields : [], priority: Number(body.priority || 100), created_by: admin.id }).select("*").single(); if (created.error) throw created.error; result=created.data; resourceType="business_authorization_policy"; resourceId=created.data.id;
    } else if (operation === "activate_policy") {
      const id=text(body,"id"); const updated=await supabase.from("business_authorization_policies").update({ status:"active",approved_by:admin.id,approved_at:new Date().toISOString(),effective_from:body.effective_from || new Date().toISOString(),effective_until:body.effective_until || null,updated_at:new Date().toISOString() }).eq("id",id).eq("status","draft").select("*").maybeSingle(); if(updated.error) throw updated.error; if(!updated.data) return json({error:"POLICY_NOT_DRAFT",request_id:requestId},409,requestId); result=updated.data;resourceType="business_authorization_policy";resourceId=id;
    } else if (operation === "retire_policy") {
      const id=text(body,"id"); const updated=await supabase.from("business_authorization_policies").update({status:"retired",effective_until:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("status","active").select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"POLICY_NOT_ACTIVE",request_id:requestId},409,requestId);result=updated.data;resourceType="business_authorization_policy";resourceId=id;
    } else if (operation === "create_recusal") {
      const required=["org_id","user_id","business_role","subject_scope","subject_id","reason_code","reason_detail"];if(required.some(key=>!text(body,key)))return json({error:"RECUSAL_REQUIRED_FIELDS_MISSING",request_id:requestId},400,requestId);
      const created=await supabase.from("business_role_recusals").insert({org_id:body.org_id,user_id:body.user_id,business_role:body.business_role,subject_scope:body.subject_scope,subject_id:body.subject_id,reason_code:body.reason_code,reason_detail:body.reason_detail,status:"active",valid_from:body.valid_from || new Date().toISOString(),valid_until:body.valid_until || null,approved_by:admin.id}).select("*").single();if(created.error)throw created.error;result=created.data;resourceType="business_role_recusal";resourceId=created.data.id;
    } else if (operation === "release_recusal") {
      const id=text(body,"id");const updated=await supabase.from("business_role_recusals").update({status:"released",released_by:admin.id,released_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("status","active").select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"RECUSAL_NOT_ACTIVE",request_id:requestId},409,requestId);result=updated.data;resourceType="business_role_recusal";resourceId=id;
    } else if (operation === "create_metric") {
      const required=["metric_key","version","name","definition"];if(required.some(key=>!text(body,key)))return json({error:"METRIC_REQUIRED_FIELDS_MISSING",request_id:requestId},400,requestId);
      const created=await supabase.from("metric_definitions").insert({org_id:body.org_id || null,metric_key:body.metric_key,version:body.version,name:body.name,definition:body.definition,numerator_definition:body.numerator_definition || null,denominator_definition:body.denominator_definition || null,source_definition:body.source_definition && typeof body.source_definition==="object"?body.source_definition:{},freshness_sla_minutes:Number(body.freshness_sla_minutes || 1440),status:"draft"}).select("*").single();if(created.error)throw created.error;result=created.data;resourceType="metric_definition";resourceId=created.data.id;
    } else if (operation === "activate_metric") {
      const id=text(body,"id");const updated=await supabase.from("metric_definitions").update({status:"active",approved_by:admin.id,approved_at:new Date().toISOString()}).eq("id",id).eq("status","draft").select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"METRIC_NOT_DRAFT",request_id:requestId},409,requestId);result=updated.data;resourceType="metric_definition";resourceId=id;
    } else if (operation === "record_metric_observation") {
      const definitionId=text(body,"metric_definition_id");const definition=await supabase.from("metric_definitions").select("id,status,freshness_sla_minutes").eq("id",definitionId).maybeSingle();if(definition.error)throw definition.error;if(!definition.data)return json({error:"METRIC_NOT_FOUND",request_id:requestId},404,requestId);
      const dataClass=text(body,"data_class") as "production"|"sample"|"test"|"diagnostic"|"unclassified";const sourceStatus=text(body,"source_status") as "verified"|"manual_unverified"|"unavailable";const observedAt=text(body,"observed_at");const trust=assessMetricTrust({observedAt,evaluatedAt:new Date().toISOString(),freshnessSlaMinutes:Number(definition.data.freshness_sla_minutes || 1440),definitionStatus:definition.data.status,sourceStatus,dataClass});
      const created=await supabase.from("metric_observations").upsert({org_id:body.org_id,metric_definition_id:definitionId,subject_scope:body.subject_scope,subject_id:body.subject_id,project_id:body.project_id || null,period_key:body.period_key,current_value:body.current_value ?? null,baseline_value:body.baseline_value ?? null,previous_forecast_value:body.previous_forecast_value ?? null,latest_forecast_value:body.latest_forecast_value ?? null,currency:body.currency || null,unit:body.unit || null,source_type:body.source_type,source_id:body.source_id,source_status:sourceStatus,observed_at:observedAt,freshness_status:trust.freshnessStatus,trust_status:trust.trustStatus,data_owner_user_id:body.data_owner_user_id || null,data_class:dataClass,evidence_ids:Array.isArray(body.evidence_ids)?body.evidence_ids:[],risk_acceptance_note:body.risk_acceptance_note || null,created_by:admin.id},{onConflict:"org_id,metric_definition_id,subject_scope,subject_id,period_key,source_type,source_id"}).select("*").single();if(created.error)throw created.error;result={observation:created.data,trust};resourceType="metric_observation";resourceId=created.data.id;
    } else if (operation === "create_sync_contract") {
      const required=["fact_key","source_system","target_system","direction","refresh_policy","idempotency_definition","deletion_semantics","compensation_strategy","reconciliation_owner_role"];if(required.some(key=>!text(body,key)))return json({error:"SYNC_CONTRACT_REQUIRED_FIELDS_MISSING",request_id:requestId},400,requestId);
      const created=await supabase.from("data_sync_contracts").insert({org_id:body.org_id || null,fact_key:body.fact_key,source_system:body.source_system,target_system:body.target_system,direction:body.direction,refresh_policy:body.refresh_policy,idempotency_definition:body.idempotency_definition,deletion_semantics:body.deletion_semantics,compensation_strategy:body.compensation_strategy,reconciliation_owner_role:body.reconciliation_owner_role,status:"draft",version:Number(body.version||1)}).select("*").single();if(created.error)throw created.error;result=created.data;resourceType="data_sync_contract";resourceId=created.data.id;
    } else if (operation === "activate_sync_contract") {
      const id=text(body,"id");const updated=await supabase.from("data_sync_contracts").update({status:"active",approved_by:admin.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("status","draft").select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"SYNC_CONTRACT_NOT_DRAFT",request_id:requestId},409,requestId);result=updated.data;resourceType="data_sync_contract";resourceId=id;
    } else if (operation === "scan_coverage_gaps") {
      const orgId=text(body,"org_id");if(!orgId)return json({error:"ORG_ID_REQUIRED",request_id:requestId},400,requestId);const scanned=await supabase.rpc("scan_business_role_coverage_gaps_tx",{p_org_id:orgId,p_due_at:body.due_at || new Date(Date.now()+86400000).toISOString()});if(scanned.error)throw scanned.error;result=scanned.data;resourceType="business_role_coverage_scan";resourceId=orgId;
    } else if (operation === "create_coverage_gap") {
      const created=await supabase.from("business_role_coverage_gaps").upsert({org_id:body.org_id,subject_scope:body.subject_scope,subject_id:body.subject_id,required_business_role:body.required_business_role,source_type:body.source_type,source_id:body.source_id,status:"open",owner_user_id:body.owner_user_id || null,due_at:body.due_at},{onConflict:"org_id,subject_scope,subject_id,required_business_role,source_type,source_id"}).select("*").single();if(created.error)throw created.error;result=created.data;resourceType="business_role_coverage_gap";resourceId=created.data.id;
    } else if (operation === "resolve_coverage_gap") {
      const id=text(body,"id");const updated=await supabase.from("business_role_coverage_gaps").update({status:"closed",resolution_note:body.resolution_note,verified_by:admin.id,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).in("status",["open","assigned","verified"]).select("*").maybeSingle();if(updated.error)throw updated.error;if(!updated.data)return json({error:"COVERAGE_GAP_NOT_OPEN",request_id:requestId},409,requestId);result=updated.data;resourceType="business_role_coverage_gap";resourceId=id;
    } else return json({ error: "UNSUPPORTED_OPERATION", request_id: requestId }, 400, requestId);
    await writeOperationAudit({user:admin,action:`operating_model_${operation}`,resourceType,resourceId,status:"succeeded",severity:"high",summary:`运行模型配置：${operation}`,detail:{operation},requestId});
    return json({ status:"succeeded",result,request_id:requestId },200,requestId);
  } catch(error){const detail=error instanceof Error?error.message:"unknown";return json({error:"OPERATING_MODEL_OPERATION_FAILED",detail,request_id:requestId},/duplicate|conflict|not active|not draft/i.test(detail)?409:/does not exist|schema cache/i.test(detail)?503:500,requestId);}
}
