"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { readStoredBusinessContext } from "@/features/operating-model/client-context";

const TABLES = [
  ["project", "项目台账"], ["milestone", "里程碑"], ["task", "任务"], ["risk", "风险"],
  ["contract", "合同"], ["payment", "回款"], ["cost", "成本"], ["syncLedger", "同步流水"],
] as const;

type Connection = { app_id?: string; table_mapping?: Record<string, string>; status?: string; version?: number; credentials_configured?: boolean; updated_at?: string };

export default function OrganizationFeishuConnectionPage() {
  const context = useMemo(() => readStoredBusinessContext(), []); const orgId = context?.orgId || "";
  const [connection, setConnection] = useState<Connection | null>(null); const [source, setSource] = useState(""); const [appId, setAppId] = useState(""); const [appSecret, setAppSecret] = useState(""); const [baseToken, setBaseToken] = useState(""); const [tables, setTables] = useState<Record<string, string>>(Object.fromEntries(TABLES.map(([key]) => [key, ""]))); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { if (!orgId) { setNotice("请先在顶部选择组织业务身份。"); return; } const response = await fetch(`/api/integrations/feishu/organization-connection?org_id=${encodeURIComponent(orgId)}`, { cache: "no-store" }); const body = await response.json() as { connection?: Connection; source?: string; detail?: string; error?: string }; if (!response.ok) { setNotice(body.detail || body.error || "组织飞书配置读取失败"); return; } setConnection(body.connection ?? null); setSource(body.source || "missing"); setAppId(body.connection?.app_id || ""); setTables(current => ({ ...current, ...(body.connection?.table_mapping || {}) })); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [orgId]);
  async function save() { setBusy(true); setNotice(""); try { const response = await fetch(`/api/integrations/feishu/organization-connection?org_id=${encodeURIComponent(orgId)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ app_id: appId, app_secret: appSecret, base_token: baseToken, table_mapping: tables, expected_version: connection?.version || 0, idempotency_key: `organization-feishu:${crypto.randomUUID()}` }) }); const body = await response.json() as { connection?: Connection; detail?: string; error?: string; missing_tables?: string[] }; if (!response.ok) throw new Error(body.detail || body.error || (body.missing_tables?.length ? `缺少表映射：${body.missing_tables.join("、")}` : "保存失败")); setConnection(body.connection ?? null); setAppSecret(""); setBaseToken(""); setNotice("组织共享飞书连接已加密保存。成员读取共享 Base 时使用此连接，个人写入仍使用各自的个人飞书连接。"); } catch (error) { setNotice(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  return <main style={{ minHeight: "100vh", background: "var(--bg)", padding: 28 }}><div style={{ maxWidth: 980, margin: "0 auto" }}><header style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><div><Link href="/integration-center" style={{ color: "var(--text2)", textDecoration: "none" }}>← 返回数据与集成中心</Link><h1 style={{ marginTop: 12 }}>组织共享飞书项目台账</h1><p style={{ color: "var(--text2)", lineHeight: 1.8, marginTop: 8 }}>组织连接只用于读取共享 Base 和定时对账；消息、任务、文档及记录写回必须使用操作人的个人飞书连接，不会回退到管理员身份。</p></div><span className="tag tag-purple">{source === "organization" ? "数据库加密配置" : source === "organization_environment" ? "组织环境配置" : "待配置"}</span></header>{notice && <aside className="card" style={{ marginTop: 16, color: notice.includes("失败") || notice.includes("缺少") ? "var(--red)" : "var(--accent2)" }}>{notice}</aside>}<section className="card" style={{ marginTop: 16 }}><div className="section-title">应用身份与 Base</div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 10 }}><input className="input" value={appId} onChange={event => setAppId(event.target.value)} placeholder="App ID"/><input className="input" type="password" value={appSecret} onChange={event => setAppSecret(event.target.value)} placeholder="App Secret（保存后不回显）"/><input className="input" type="password" value={baseToken} onChange={event => setBaseToken(event.target.value)} placeholder="多维表格 App Token（保存后不回显）"/></div><div className="section-title" style={{ marginTop: 18 }}>八类中文业务表映射</div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 10 }}>{TABLES.map(([key, label]) => <label key={key} style={{ display: "grid", gap: 5, color: "var(--text2)" }}>{label}<input className="input" value={tables[key] || ""} onChange={event => setTables(current => ({ ...current, [key]: event.target.value }))} placeholder={`${label} Table ID`}/></label>)}</div><button className="btn-primary" style={{ marginTop: 16 }} disabled={busy || !orgId || !appId || !appSecret || !baseToken || TABLES.some(([key]) => !tables[key])} onClick={() => void save()}>{busy ? "加密保存中…" : "保存组织共享连接"}</button>{connection?.updated_at && <p style={{ color: "var(--text2)", marginTop: 10 }}>最近更新：{new Date(connection.updated_at).toLocaleString("zh-CN")} · 版本 {connection.version}</p>}</section></div></main>;
}
