import { createHash } from "node:crypto";
import { getAuthSupabase, getCurrentUser } from "@/features/auth/server";
import { canReviewClosureAssessment, evaluateClosureGate } from "@/features/operating-model/closure-knowledge";
import { resolveBusinessContext, type BusinessRole, type SubjectScope } from "@/features/operating-model/context";
import { listBusinessRoleAssignments, loadContextProjectIdentityMappings, type ManagementSignalRecord } from "@/features/operating-model/persistence";
import { writeOperationAudit } from "@/features/security/repository";

export const runtime = "nodejs";
const ROLES = new Set<BusinessRole>(["pm", "operations", "pmo", "sponsor", "business_owner", "finance", "quality"]);
function json(body: unknown, status = 200, requestId = crypto.randomUUID()) { return Response.json(body, { status, headers: { "Cache-Control": "no-store", "X-Request-Id": requestId } }); }

async function contextFor(request: Request) {
  const user = await getCurrentUser(); if (!user) return { error: "UNAUTHORIZED", status: 401 } as const; const url = new URL(request.url); const role = (url.searchParams.get("role") || "") as BusinessRole; const orgId = url.searchParams.get("org_id") || ""; const subjectScope = (url.searchParams.get("subject_scope") || "") as SubjectScope; const subjectId = url.searchParams.get("subject_id") || ""; const dataClass = (url.searchParams.get("data_class") || "production") as ManagementSignalRecord["dataClass"];
  if (!ROLES.has(role) || !orgId || !subjectScope || !subjectId) return { error: "CLOSURE_CONTEXT_REQUIRED", status: 403 } as const; const assignments = await listBusinessRoleAssignments(user.id); if (assignments.status !== "succeeded") return { error: "P17_STORAGE_NOT_CONFIGURED", detail: assignments.warning, status: 503 } as const; const context = resolveBusinessContext({ user: { id: user.id, systemRole: user.role }, assignments: assignments.data ?? [], requestedRole: role, requestedOrgId: orgId, requestedSubjectScope: subjectScope, requestedSubjectId: subjectId }); if (!context) return { error: "BUSINESS_CONTEXT_FORBIDDEN", status: 403 } as const; const mappings = await loadContextProjectIdentityMappings({ context, dataClass }); if (mappings.status !== "succeeded") return { error: "PROJECT_SCOPE_MAPPING_FAILED", detail: mappings.warning, status: mappings.status === "not_configured" ? 503 : 500 } as const; const projectIds = [...new Set((mappings.data ?? []).map(item => item.projectId))]; const requestedProjectId = url.searchParams.get("project_id") || (context.subjectScope === "project" ? context.subjectId : projectIds[0] || ""); if (!requestedProjectId || !projectIds.includes(requestedProjectId)) return { error: "PROJECT_OUTSIDE_CONTEXT", status: 403 } as const; return { user, role, context, dataClass, projectIds, projectId: requestedProjectId } as const;
}

async function loadClosure(scope: Exclude<Awaited<ReturnType<typeof contextFor>>, { error: string }>) {
  const supabase = getAuthSupabase(); const projectId = scope.projectId;
  const [project, tasks, deliverables, risks, issues, changes, reports, projectEvidence, contracts, benefits, assessments, candidates, reuse] = await Promise.all([
    supabase.from("projects").select("id,name,project_level,status,data_class").eq("id", projectId).eq("org_id", scope.context.orgId).eq("data_class", scope.dataClass).maybeSingle(),
    supabase.from("tasks").select("id,status").eq("project_id", projectId),
    supabase.from("project_lifecycle_states").select("id,status").eq("project_id", projectId).eq("object_type", "deliverable").eq("data_class", scope.dataClass),
    supabase.from("risks").select("id,status,risk_level,score").eq("project_id", projectId),
    supabase.from("project_issues").select("id,status").eq("project_id", projectId),
    supabase.from("project_changes").select("id,status").eq("project_id", projectId),
    supabase.from("reports").select("id,type").eq("project_id", projectId).eq("type", "acceptance"),
    supabase.from("evidence_links").select("id,evidence_type,title,verified_at,valid_until").eq("subject_type", "project").eq("subject_id", projectId),
    supabase.from("contracts").select("id").eq("project_id", projectId),
    supabase.from("project_benefit_baselines").select("id,status").eq("project_id", projectId).eq("org_id", scope.context.orgId).eq("data_class", scope.dataClass),
    supabase.from("project_closure_assessments").select("*").eq("project_id", projectId).eq("org_id", scope.context.orgId).eq("data_class", scope.dataClass).order("created_at", { ascending: false }).limit(20),
    supabase.from("knowledge_items").select("id,page_id,title,status,knowledge_type,applicable_scenarios,metadata,updated_at").contains("metadata", { source_project_id: projectId }).order("updated_at", { ascending: false }).limit(100),
    supabase.from("knowledge_reuse_events").select("*").or(`source_project_id.eq.${projectId},target_project_id.eq.${projectId}`).eq("org_id", scope.context.orgId).order("created_at", { ascending: false }).limit(100),
  ]);
  const errors = [project, tasks, deliverables, risks, issues, changes, reports, projectEvidence, contracts, benefits, assessments, candidates, reuse].find(item => item.error)?.error; if (errors) throw new Error(errors.message); if (!project.data) throw new Error("项目不存在或数据分类不匹配"); const candidateIds = (candidates.data ?? []).map(item => item.id); const impacts = candidateIds.length ? await supabase.from("knowledge_change_impact_links").select("*").in("knowledge_item_id", candidateIds).order("created_at", { ascending: false }).limit(200) : { data: [], error: null }; if (impacts.error) throw new Error(impacts.error.message); const contractIds = (contracts.data ?? []).map(item => item.id); const payments = contractIds.length ? await supabase.from("payment_milestones").select("amount,status").in("contract_id", contractIds) : { data: [], error: null }; if (payments.error) throw new Error(payments.error.message);
  const open = (status: unknown) => !["completed", "closed", "done", "cancelled", "approved", "accepted", "resolved"].includes(String(status || "").toLowerCase()); const evidence = projectEvidence.data ?? [];
  const facts = { openTasks: (tasks.data ?? []).filter(item => open(item.status)).length, unacceptedDeliverables: (deliverables.data ?? []).filter(item => open(item.status)).length, openHighRisks: (risks.data ?? []).filter(item => open(item.status) && (String(item.risk_level).includes("高") || Number(item.score || 0) >= 12)).length, openIssues: (issues.data ?? []).filter(item => open(item.status)).length, pendingChanges: (changes.data ?? []).filter(item => open(item.status)).length, acceptanceEvidence: (reports.data ?? []).length + evidence.filter(item => item.evidence_type === "acceptance_record" && item.verified_at).length, outstandingReceivable: (payments.data ?? []).filter(item => item.status !== "paid").reduce((sum, item) => sum + Number(item.amount || 0), 0), archiveEvidence: evidence.filter(item => item.evidence_type === "archive_package" && item.verified_at).length, handoverEvidence: evidence.filter(item => item.evidence_type === "knowledge_handover" && item.verified_at).length, benefitBaselineRequired: ["S", "A"].includes(String(project.data.project_level || "")), benefitBaselineCount: (benefits.data ?? []).length };
  return { project: project.data, gate: evaluateClosureGate(facts), evidence, assessments: assessments.data ?? [], knowledgeCandidates: candidates.data ?? [], impactLinks: impacts.data ?? [], reuseEvents: reuse.data ?? [] };
}

export async function GET(request: Request) { const requestId = crypto.randomUUID(); const scope = await contextFor(request); if ("error" in scope) return json({ error: scope.error, detail: "detail" in scope ? scope.detail : undefined, request_id: requestId }, scope.status, requestId); try { const data = await loadClosure(scope); return json({ status: "succeeded", context: scope.context, data_class: scope.dataClass, source: { type: "supabase", fallback_used: false }, projects: scope.projectIds, ...data, request_id: requestId }, 200, requestId); } catch (error) { return json({ error: "CLOSURE_DATA_UNAVAILABLE", detail: error instanceof Error ? error.message : "unknown", request_id: requestId }, 503, requestId); } }

export async function POST(request: Request) {
  const requestId = crypto.randomUUID(); const scope = await contextFor(request); if ("error" in scope) return json({ error: scope.error, detail: "detail" in scope ? scope.detail : undefined, request_id: requestId }, scope.status, requestId); let body: Record<string, unknown>; try { body = await request.json() as Record<string, unknown>; } catch { return json({ error: "INVALID_JSON", request_id: requestId }, 400, requestId); } const operation = String(body.operation || ""); const supabase = getAuthSupabase();
  try { let resourceId = "";
    if (operation === "assess_closure") { const data = await loadClosure(scope); const [latest, closureState, projectState] = await Promise.all([supabase.from("project_closure_assessments").select("assessment_version").eq("project_id", scope.projectId).eq("data_class", scope.dataClass).order("assessment_version", { ascending: false }).limit(1).maybeSingle(), supabase.from("project_lifecycle_states").select("id").eq("project_id", scope.projectId).eq("object_type", "closure").eq("data_class", scope.dataClass).order("updated_at", { ascending: false }).limit(1).maybeSingle(), supabase.from("project_lifecycle_states").select("id").eq("project_id", scope.projectId).eq("object_type", "project").eq("data_class", scope.dataClass).limit(1).maybeSingle()]); if (latest.error || closureState.error || projectState.error) throw latest.error || closureState.error || projectState.error; const lifecycleStateId = closureState.data?.id || projectState.data?.id; if (!lifecycleStateId) return json({ error: "CLOSURE_LIFECYCLE_NOT_INITIALIZED", detail: "请先在项目生命周期中初始化项目或收尾对象。", request_id: requestId }, 409, requestId); const assessment = await supabase.from("project_closure_assessments").insert({ org_id: scope.context.orgId, project_id: scope.projectId, assessment_version: Number(latest.data?.assessment_version || 0) + 1, fact_snapshot: data.gate.facts, blockers: data.gate.blockers, ready: data.gate.ready, status: data.gate.ready ? "submitted" : "evidence_pending", assessed_by: scope.user.id, lifecycle_state_id: lifecycleStateId, data_class: scope.dataClass, request_id: requestId }).select("id").single(); if (assessment.error) throw assessment.error; resourceId = assessment.data.id;
    } else if (operation === "review_closure") { if (!["pmo", "sponsor"].includes(scope.role)) return json({ error: "CLOSURE_REVIEW_ROLE_REQUIRED", request_id: requestId }, 403, requestId); const assessmentId = String(body.assessment_id || ""); const decision = body.decision === "reject" ? "reject" : body.decision === "approve" ? "approve" : ""; const reviewNote = String(body.review_note || "").trim(); if (!assessmentId || !decision || !reviewNote) return json({ error: "ASSESSMENT_DECISION_AND_REVIEW_NOTE_REQUIRED", request_id: requestId }, 400, requestId); const current = await supabase.from("project_closure_assessments").select("id,status,ready").eq("id", assessmentId).eq("org_id", scope.context.orgId).eq("project_id", scope.projectId).eq("data_class", scope.dataClass).maybeSingle(); if (current.error) throw current.error; if (!current.data) return json({ error: "CLOSURE_ASSESSMENT_NOT_FOUND", request_id: requestId }, 404, requestId); const latest = await loadClosure(scope); if (decision === "approve" && !canReviewClosureAssessment({ status: current.data.status, ready: current.data.ready, role: scope.role, currentGateReady: latest.gate.ready })) return json({ error: "CLOSURE_GATE_CHANGED_OR_NOT_REVIEWABLE", blockers: latest.gate.blockers, request_id: requestId }, 409, requestId); if (decision === "reject" && current.data.status !== "submitted") return json({ error: "CLOSURE_ASSESSMENT_NOT_REVIEWABLE", request_id: requestId }, 409, requestId); const reviewed = await supabase.from("project_closure_assessments").update({ status: decision === "approve" ? "approved" : "rejected", reviewed_by: scope.user.id, review_note: reviewNote, reviewed_at: new Date().toISOString() }).eq("id", assessmentId).eq("status", "submitted").select("id").maybeSingle(); if (reviewed.error) throw reviewed.error; if (!reviewed.data) return json({ error: "CLOSURE_REVIEW_CONFLICT", request_id: requestId }, 409, requestId); resourceId = reviewed.data.id;
    } else if (operation === "create_knowledge_candidate") { const title = String(body.title || "").trim(); const summary = String(body.summary || "").trim(); if (!title || !summary) return json({ error: "TITLE_AND_SUMMARY_REQUIRED", request_id: requestId }, 400, requestId); const pageId = `project-${scope.projectId}-knowledge-${requestId}`; const hash = createHash("sha256").update(summary).digest("hex"); const created = await supabase.rpc("create_closure_knowledge_candidate_tx", { p_page_id: pageId, p_title: title, p_knowledge_type: body.knowledge_type || "lessons_learned", p_owner_name: scope.user.name || scope.user.email, p_domains: Array.isArray(body.domains) ? body.domains : ["project-management"], p_tags: Array.isArray(body.tags) ? body.tags : [], p_source_refs: [`project:${scope.projectId}`, ...(Array.isArray(body.source_refs) ? body.source_refs : [])], p_confidentiality: body.confidentiality || "internal", p_applicable_scenarios: Array.isArray(body.applicable_scenarios) ? body.applicable_scenarios : [], p_metadata: { org_id: scope.context.orgId, source_project_id: scope.projectId, data_class: scope.dataClass, summary, source_decision_ids: body.source_decision_ids || [], source_action_ids: body.source_action_ids || [], observed_effect: body.observed_effect || "", applicability_conditions: body.applicability_conditions || "" }, p_content_hash: hash, p_actor_user_id: scope.user.id, p_actor_name: scope.user.name || scope.user.email }); if (created.error) throw created.error; resourceId = String((created.data as { knowledge_item?: { id?: string } } | null)?.knowledge_item?.id || ""); if (!resourceId) throw new Error("P24_KNOWLEDGE_CANDIDATE_TRANSACTION_INCOMPLETE");
    } else if (operation === "publish_knowledge_candidate") { if (!["pmo", "quality"].includes(scope.role)) return json({ error: "KNOWLEDGE_REVIEW_ROLE_REQUIRED", request_id: requestId }, 403, requestId); const itemId = String(body.knowledge_item_id || ""); const reviewNote = String(body.review_note || "").trim(); if (!itemId || !reviewNote) return json({ error: "KNOWLEDGE_ITEM_AND_REVIEW_NOTE_REQUIRED", request_id: requestId }, 400, requestId); const allowedTargets = new Set(["risk", "planning", "reports", "templates", "governance", "role-assistant", "training"]); const requestedTargets = Array.isArray(body.impact_targets) ? body.impact_targets.map(String) : ["risk", "planning", "reports", "templates"]; const targets = [...new Set(requestedTargets.filter(target => allowedTargets.has(target)))]; if (targets.length === 0) return json({ error: "IMPACT_TARGETS_REQUIRED", request_id: requestId }, 400, requestId); const published = await supabase.rpc("publish_closure_knowledge_candidate_tx", { p_knowledge_item_id: itemId, p_source_project_id: scope.projectId, p_actor_user_id: scope.user.id, p_actor_name: scope.user.name || scope.user.email, p_review_note: reviewNote, p_impact_targets: targets, p_request_id: requestId }); if (published.error) throw published.error; resourceId = itemId;
    } else if (operation === "record_reuse") { const targetProjectId = String(body.target_project_id || ""); const knowledgeItemId = String(body.knowledge_item_id || ""); const reason = String(body.recommendation_reason || "").trim(); if (!scope.projectIds.includes(targetProjectId)) return json({ error: "TARGET_PROJECT_OUTSIDE_CONTEXT", request_id: requestId }, 403, requestId); if (!knowledgeItemId || !reason) return json({ error: "KNOWLEDGE_ITEM_AND_REASON_REQUIRED", request_id: requestId }, 400, requestId); const knowledge = await supabase.from("knowledge_items").select("id,metadata").eq("id", knowledgeItemId).eq("status", "published").maybeSingle(); if (knowledge.error) throw knowledge.error; if (!knowledge.data) return json({ error: "PUBLISHED_KNOWLEDGE_NOT_FOUND", request_id: requestId }, 404, requestId); const sourceProjectId = String((knowledge.data.metadata as Record<string, unknown> | null)?.source_project_id || ""); if (sourceProjectId && !scope.projectIds.includes(sourceProjectId)) return json({ error: "SOURCE_PROJECT_OUTSIDE_CONTEXT", request_id: requestId }, 403, requestId); const reuse = await supabase.from("knowledge_reuse_events").insert({ org_id: scope.context.orgId, knowledge_item_id: knowledgeItemId, source_project_id: sourceProjectId || null, target_project_id: targetProjectId, recommendation_reason: reason, applicability: body.applicability || {}, status: "recommended", actor_user_id: scope.user.id, usage_note: body.usage_note || null, outcome: null, effect_score: null, data_class: scope.dataClass }).select("id").single(); if (reuse.error) throw reuse.error; resourceId = reuse.data.id;
    } else if (operation === "update_reuse") { const reuseId = String(body.reuse_event_id || ""); const action = String(body.action || ""); const current = await supabase.from("knowledge_reuse_events").select("id,status,target_project_id").eq("id", reuseId).eq("org_id", scope.context.orgId).eq("data_class", scope.dataClass).maybeSingle(); if (current.error) throw current.error; if (!current.data || !scope.projectIds.includes(String(current.data.target_project_id || ""))) return json({ error: "REUSE_EVENT_NOT_FOUND", request_id: requestId }, 404, requestId); const transitions: Record<string, Record<string, string>> = { recommended: { accept: "accepted", reject: "rejected" }, accepted: { apply: "applied" }, applied: { review_effect: "effect_reviewed" } }; const next = transitions[current.data.status]?.[action]; if (!next) return json({ error: "REUSE_TRANSITION_NOT_ALLOWED", request_id: requestId }, 409, requestId); if (action === "reject" && !String(body.rejection_reason || "").trim()) return json({ error: "REJECTION_REASON_REQUIRED", request_id: requestId }, 400, requestId); if (action === "apply" && !String(body.usage_note || "").trim()) return json({ error: "USAGE_NOTE_REQUIRED", request_id: requestId }, 400, requestId); if (action === "review_effect" && (!String(body.outcome || "").trim() || ![1, 2, 3, 4, 5].includes(Number(body.effect_score)))) return json({ error: "OUTCOME_AND_EFFECT_SCORE_REQUIRED", request_id: requestId }, 400, requestId); if (action === "review_effect" && !["pmo", "quality", "sponsor"].includes(scope.role)) return json({ error: "REUSE_EFFECT_REVIEW_ROLE_REQUIRED", request_id: requestId }, 403, requestId); const updated = await supabase.from("knowledge_reuse_events").update({ status: next, rejection_reason: action === "reject" ? String(body.rejection_reason).trim() : null, usage_note: action === "apply" ? String(body.usage_note).trim() : undefined, outcome: action === "review_effect" ? String(body.outcome).trim() : undefined, effect_score: action === "review_effect" ? Number(body.effect_score) : undefined, updated_at: new Date().toISOString() }).eq("id", reuseId).eq("status", current.data.status).select("id").maybeSingle(); if (updated.error) throw updated.error; if (!updated.data) return json({ error: "REUSE_TRANSITION_CONFLICT", request_id: requestId }, 409, requestId); resourceId = updated.data.id;
    } else if (operation === "update_impact") { if (!["pmo", "quality"].includes(scope.role)) return json({ error: "KNOWLEDGE_IMPACT_ROLE_REQUIRED", request_id: requestId }, 403, requestId); const impactId = String(body.impact_id || ""); const action = String(body.action || ""); const evidence = Array.isArray(body.closure_evidence) ? body.closure_evidence.filter(item => typeof item === "string" && item.trim()).map(item => item.trim()) : []; const impact = await supabase.from("knowledge_change_impact_links").select("id,status,knowledge_item_id").eq("id", impactId).maybeSingle(); if (impact.error) throw impact.error; if (!impact.data) return json({ error: "IMPACT_LINK_NOT_FOUND", request_id: requestId }, 404, requestId); const item = await supabase.from("knowledge_items").select("id").eq("id", impact.data.knowledge_item_id).contains("metadata", { source_project_id: scope.projectId }).maybeSingle(); if (item.error) throw item.error; if (!item.data) return json({ error: "IMPACT_LINK_OUTSIDE_PROJECT", request_id: requestId }, 403, requestId); const transitions: Record<string, Record<string, string>> = { pending_review: { start: "in_progress", no_change: "no_change" }, in_progress: { mark_updated: "updated", no_change: "no_change" }, updated: { close: "closed" }, no_change: { close: "closed" } }; const next = transitions[impact.data.status]?.[action]; if (!next) return json({ error: "IMPACT_TRANSITION_NOT_ALLOWED", request_id: requestId }, 409, requestId); if (["no_change", "mark_updated", "close"].includes(action) && evidence.length === 0) return json({ error: "IMPACT_CLOSURE_EVIDENCE_REQUIRED", request_id: requestId }, 400, requestId); const changed = await supabase.from("knowledge_change_impact_links").update({ status: next, closure_evidence: evidence.length ? evidence : undefined, updated_at: new Date().toISOString() }).eq("id", impactId).eq("status", impact.data.status).select("id").maybeSingle(); if (changed.error) throw changed.error; if (!changed.data) return json({ error: "IMPACT_TRANSITION_CONFLICT", request_id: requestId }, 409, requestId); resourceId = changed.data.id;
    } else return json({ error: "UNSUPPORTED_OPERATION", request_id: requestId }, 400, requestId);
    await writeOperationAudit({ user: scope.user, action: `closure_knowledge_${operation}`, resourceType: "closure_knowledge", resourceId, status: "succeeded", severity: operation.includes("publish") ? "high" : "medium", summary: `收尾与知识动作：${operation}`, detail: { projectId: scope.projectId, role: scope.role }, requestId }); return json({ status: "succeeded", id: resourceId, request_id: requestId }, 201, requestId);
  } catch (error) { return json({ error: "CLOSURE_KNOWLEDGE_WRITE_FAILED", detail: error instanceof Error ? error.message : "unknown", request_id: requestId }, 503, requestId); }
}
